# Generated by Django 4.1 on 2023-09-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoplist",
            name="add_day",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="add_day"
            ),
        ),
    ]
