# Generated by Django 4.1 on 2023-09-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0002_shoplist_add_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoplist",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="shopname"
            ),
        ),
    ]
