# Generated by Django 4.1 on 2023-12-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0003_alter_shoplist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoplist",
            name="frequency_of_visit",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="frequency_of_visit"
            ),
        ),
        migrations.AddField(
            model_name="shoplist",
            name="last_visit",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="last_visit"
            ),
        ),
    ]
